---
- hosts: OSEv3
  tasks:
  - name: Install the following base packages
    yum: name="{{ item }}" state=present
    with_items:
      - wget
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - git
      - python-pip
      - kexec-tools
      - sos
      - psacct
      - atomic-openshift-docker-excluder
      - ntp

  - name: Install Docker
    yum: name=docker state=present

  - name: Enable Docker Service
    service: name=docker enabled=yes

  - name: Start Docker Service
    service: name=docker state=started
